#!/usr/bin/env bb

;; =============================================================================
;;  create_conf.clj — Generate a default spellbook.conf
;;
;;  Prompts for the root install directory, then writes spellbook.conf there.
;;
;;  Usage:
;;    bb create_conf.clj
;; =============================================================================

(ns create-conf
  (:require [babashka.fs :as fs]
            [clojure.string :as str]))

;; ---------------------------------------------------------------------------
;; Helpers
;; ---------------------------------------------------------------------------

(def windows?
  (str/starts-with? (str/lower-case (System/getProperty "os.name")) "windows"))

(defn home []
  (if windows?
    (or (System/getenv "USERPROFILE") (System/getProperty "user.home"))
    (System/getProperty "user.home")))

(defn p [& parts]
  (str (apply fs/path (map str parts))))

;; ---------------------------------------------------------------------------
;; Conf generation
;; ---------------------------------------------------------------------------

(defn build-conf [root]
  (str/join "\n"
    ["; +============================================================+"
     "; |             * S P E L L B O O K . C O N F *              |"
     "; |         Generated by create_conf.clj                      |"
     "; +============================================================+"
     ""
     "[alias]"
     "contacts = people"
     "tasks    = todo"
     ""
     "[tags]"
     "; ── Core Personal ─────────────────────────────────────────────"
     "contacts" "events" "todo" "email" "communication"
     "calendar" "alarm" "journal" "note" "datum" "name"
     "; ── Crafts & Trades ────────────────────────────────────────────"
     "tailoring" "agriculture" "architecture" "martial-arts" "trade"
     "cooking" "metallurgy" "musical-instrument" "strategy-game"
     "calligraphy" "Chinese-painting"
     "; ── Trivium ───────────────────────────────────────────────────"
     "rhetoric" "grammar" "logic"
     "; ── Quadrivium ────────────────────────────────────────────────"
     "astronomy" "arithmetic" "geometry" "music"
     "; ── Academic Disciplines ──────────────────────────────────────"
     "anthropology" "English" "literature" "fine-arts" "philosophy"
     "psychology" "sociology" "journalism" "economics" "law"
     "communications" "creative-arts" "art" "history"
     "formal-science" "natural-science" "technology"
     "; ── Life Areas ────────────────────────────────────────────────"
     "personal" "work"
     ""
     "[spellbook]"
     (str "root          = " root)
     (str "inbox         = " (p root "inbox"))
     (str "archive       = " (p root "content" "archive"))
     (str "notes         = " (p root "content" "notes"))
     (str "journal       = " (p root "content" "journal"))
     (str "maps          = " (p root "content" "maps"))
     (str "taghub        = " (p root "content" "maps" "tag-hub"))
     (str "wiki          = " (p root "content" "maps" "wiki"))
     (str "hubs          = " (p root "content" "maps" "hubs"))
     (str "backlinks     = " (p root "content" "maps" "backlinks"))
     (str "scripts       = " (p root "infrastructure" "scripts"))
     (str "documentation = " (p root "infrastructure" "documentation"))
     (str "rituals       = " (p root "infrastructure" "rituals"))
     "ollama_host   = 127.0.0.1:11434"
     "ollama_model  = llama3.1:8b"
     "plugin_sigil  ="
     ""
     "; Rituals registered explicitly by name=path."
     "; These override any same-named .ritual file in the rituals/ directory."
     "[rituals]"
     (str "sleep         = " (p root "infrastructure" "rituals" "sleep.ritual"))
     (str "reset         = " (p root "infrastructure" "rituals" "reset.ritual"))
     (str "query         = " (p root "infrastructure" "rituals" "query.ritual"))
     (str "wiki          = " (p root "infrastructure" "rituals" "wiki.ritual"))
     ""
     "[spellbook-ignored]"
     "\"infrastructure\"" "\"projects\""
     "\"archive\"" "\"assets\"" "\"maps\""]))

;; ---------------------------------------------------------------------------
;; Entry point
;; ---------------------------------------------------------------------------

(defn -main [& _args]
  (let [default-dir (p (home) "Documents" "spellbook")
        _           (print (str "[?] Root directory [" default-dir "]: "))
        _           (flush)
        input       (str/trim (or (read-line) ""))
        install-dir (str (fs/expand-home (if (str/blank? input) default-dir input)))
        out-path    (p install-dir "spellbook.conf")]

    (println (str "[*] Writing : " out-path))

    (when (fs/exists? out-path)
      (println (str "[!] spellbook.conf already exists at: " out-path))
      (print    "    Overwrite? (y/N): ")
      (flush)
      (when (not= "y" (str/lower-case (str/trim (or (read-line) ""))))
        (println "[X] Aborted.")
        (System/exit 0)))

    (spit out-path (build-conf install-dir))
    (println (str "[OK] spellbook.conf written to: " out-path))))

(when (= *file* (System/getProperty "babashka.file"))
  (apply -main *command-line-args*))